### ISSUE TITLE
sampleCount and amplificationFactor is changed based on Audio? 

### ISSUE THREAD

**Issue by khush004** [alexey-savchenko/ASWaveformPlayerView#2]
Hey, I am trying to use this Library with server URL my URL is [http://18.206.123.150/storage/upload/sounds/2018/12/1545196015Zaalima-(Raees)-(RaagSong.Com).mp3](url).

for this code

            let waveform = try ASWaveformPlayerView(audioURL: audioURL,
                                                    sampleCount: 1024,
                                                    amplificationFactor: 500)

Should i need to change sampleCount and amplificationFactor base on Audio URL or this library is working only for local URL?

when i used URL which is given in this project then it works fine but it will not work with Server URL can you please help me?

**Comment by BinaryMalti** [comment]
> Hey, I am trying to use this Library with server URL my URL is [http://18.206.123.150/storage/upload/sounds/2018/12/1545196015Zaalima-(Raees)-(RaagSong.Com).mp3](url).
> 
> for this code
> 
> ```
>         let waveform = try ASWaveformPlayerView(audioURL: audioURL,
>                                                 sampleCount: 1024,
>                                                 amplificationFactor: 500)
> ```
> 
> Should i need to change sampleCount and amplificationFactor base on Audio URL or this library is working only for local URL?
> 
> when i used URL which is given in this project then it works fine but it will not work with Server URL can you please help me?

Have you find any solution for above?Please help me too.
